from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / 'app/src/main/java/com/example/MicScreen.kt'
MIC = ROOT / 'app/src/main/java/com/example/player/MicController.kt'
MARKER = '// MIC_RECORDING_FORMAT_V1'


def patch_main():
    text = MAIN.read_text(encoding='utf-8')
    # Always normalize the callback name before any idempotency guard. The
    # Boolean state property already generates a JVM setVoiceProcessingEnabled
    # setter, so a method with the same name causes a platform declaration clash.
    text = text.replace('micController::setVoiceProcessingEnabled', 'micController::toggleVoiceProcessing')
    text = text.replace('micController.setVoiceProcessingEnabled(', 'micController.toggleVoiceProcessing(')

    if MARKER in text:
        MAIN.write_text(text, encoding='utf-8')
        return

    text = text.replace('    var outputExpanded by remember { mutableStateOf(false) }\n', '    var outputExpanded by remember { mutableStateOf(false) }\n    var recordingFormat by remember { mutableStateOf("WAV") }\n', 1)
    text = text.replace('ActivityResultContracts.CreateDocument("audio/wav")', 'ActivityResultContracts.CreateDocument("audio/*")', 1)
    text = text.replace('micController.savePendingRecording(uri)', 'micController.savePendingRecording(uri, recordingFormat)', 1)
    text = text.replace('micController.suggestedRecordingName())', 'micController.suggestedRecordingName(recordingFormat))', 1)
    anchor = '                Spacer(Modifier.height(10.dp))\n                Button(\n                    enabled = micController.isMicEnabled || micController.isOutputRecording,'
    if anchor not in text:
        raise SystemExit('Recording button anchor not found')
    format_ui = '''                Text("Format", style = MaterialTheme.typography.labelSmall)\n                Spacer(Modifier.height(4.dp))\n                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {\n                    FilterChip(selected = recordingFormat == "WAV", onClick = { recordingFormat = "WAV" }, label = { Text("WAV") })\n                    FilterChip(selected = recordingFormat == "MP3", onClick = { recordingFormat = "MP3" }, label = { Text("MP3") })\n                }\n                Spacer(Modifier.height(10.dp))\n'''
    text = text.replace(anchor, format_ui + anchor, 1)
    MAIN.write_text(text.replace('fun MicScreen(', MARKER + '\nfun MicScreen(', 1), encoding='utf-8')


def patch_mic():
    text = MIC.read_text(encoding='utf-8')
    # Fix the actual JVM clash unconditionally, including builds where the
    # MicController has already been generated by the V5 microphone patch.
    text = re.sub(r'(@kotlin\.jvm\.JvmName\([^\n]+\)\n\s*)?fun\s+setVoiceProcessingEnabled\s*\(', r'fun toggleVoiceProcessing(', text, count=1)
    if 'fun toggleVoiceProcessing(enabled: Boolean)' not in text:
        needle = '    @SuppressLint("MissingPermission")\n    private fun applyInputRouting()'
        method = '''    fun toggleVoiceProcessing(enabled: Boolean) {\n        voiceProcessingEnabled = enabled\n        try { echoCanceler?.enabled = enabled } catch (_: Throwable) { }\n        try { noiseSuppressor?.enabled = enabled } catch (_: Throwable) { }\n        recordingStatus = if (enabled) "AEC + noise suppression enabled" else "Voice cleanup disabled"\n    }\n\n'''
        if needle not in text:
            raise SystemExit('MicController routing anchor not found')
        text = text.replace(needle, method + needle, 1)
    MIC.write_text(text, encoding='utf-8')


patch_main(); patch_mic(); print('Microphone recording/build normalization applied')
